<<<<<<< HEAD
# Test changes of this .travis.yml config before submitting them:
# http://lint.travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector
# ---------------------------------------------------------------
# Encrypt Travis CI settings using this tool by Konstantin Haase:
# https://rkh.github.io/travis-encrypt/public/index.html
# ---------------------------------------------------------------

# Travis CI Settings
#-------------------

language: android
# Turning off caching to avoid caching Issues
cache: false
# Using the new Container-Based Infrastructure
sudo: false
env:
  global:
# Initiating clean Gradle output
    - TERM=dumb
# Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
# General Android settings used in builds
    - ANDROID_TARGET=android-17
    - ANDROID_ABI=armeabi-v7a

# Encrypted Tokens
#-----------------

# Encrypted Coverity Scan Token
    - secure: "jRKgZfeAxDhqDIrySBESiij3Ot9cmVQ4CMB+IVpmf7Xjfek6By1ba7Y1lgMdLRPgvLkj3k5mMx1BMx2yeSCBp/+TZJ6Ezj3EVJ6HS2ctkAH4KzsiqlSCKiRgfOqKgzfnftCkNzXCEE3XLVLcv4iT5Ru/EBG85kEDViGrDBP+PxA="
# Encrypted internal chat Token
notifications:
  hipchat:
    - secure: "I2XmQkFCyKZHW2NeClYyl3FND80YkqLtYo+Rn3ftS4xjEg6VfGgDv6AlvQ+b+oZg7RZI6nKia9OLZxAxVBOHw6UcJJnurJx4hfAIBZAihIiNpZPj1c9wGgv4D+M6zi3rgbJRZ2Tz6IKJvHC+CD3LApeJR9kH15lDWbD7YZ0UI7E="

before_install:
# Making sure gradlew has executable permissions
    - chmod +x gradlew

android:
  components:
# We are using the latest revision of Android SDK Tools
     - platform-tools
     - tools
# The BuildTools version we are using for our project
     - build-tools-21.1.1
# System Image we use to run emulator(s) during tests
     - sys-img-armeabi-v7a-android-17
    
  licenses:
     - 'android-sdk-license-.+'
     
# Emulator Management: Create, Start and Wait
before_script:
# Inspecting running services
     - ps auxww
     - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
     - emulator -avd test -no-skin -no-audio -no-window &
     - android-wait-for-emulator
     - adb shell input keyevent 82 &
     
script: ./gradlew connectedAndroidTest --info

# Coverity Scan Settings
#-----------------------

addons:
  coverity_scan:
    project:
      name: "SecUpwN/Android-IMSI-Catcher-Detector"
    notification_email: annoyed@coverity.notifications
# Scan results: http://scan.coverity.com/projects/3346
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master
=======
# Test all changes of this .travis.yml config file before submitting them:
# https://yaml.travis-ci.org/CellularPrivacy/Android-IMSI-Catcher-Detector
# ------------------------------------------------------------------------
# Encrypt settings: https://rkh.github.io/travis-encrypt/public/index.html
# ------------------------------------------------------------------------

language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - GRADLE_OPTS="-Xmx2048m -Xms512m"
    # Encrypted Coverity Scan Token
    - secure: "jRKgZfeAxDhqDIrySBESiij3Ot9cmVQ4CMB+IVpmf7Xjfek6By1ba7Y1lgMdLRPgvLkj3k5mMx1BMx2yeSCBp/+TZJ6Ezj3EVJ6HS2ctkAH4KzsiqlSCKiRgfOqKgzfnftCkNzXCEE3XLVLcv4iT5Ru/EBG85kEDViGrDBP+PxA="

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_install:
  - 'openssl aes-256-cbc -K $encrypted_dc771c3300d2_key -iv $encrypted_dc771c3300d2_iv -in keystore.jks.enc -out keystore.jks -d || true'

install: ./gradlew clean

script: ./gradlew build check

before_deploy:
  - cd AIMSICD/build/outputs/apk; ls -la; md5sum *-normal-release.apk > md5sum.txt; sha1sum *-normal-release.apk > sha1sum.txt; cd -

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hWL8k4eTm6RBA6JtY+zL/bFFm+f2eM466kKlHBrywukSXAThgX8VzHVu9I8u9bL1yP2j8R9XHmG+C49Fy8NZ85Hmj5ECFg3dGRhfxAzr3o3deP3Kaeo+LozGhOy/z2PvOPyHS7XqOK8kk8gmoMJ9jvhz+wFAbW9GxhKLYBMn81E=
  file:
    - AIMSICD/build/outputs/apk/AIMSICD-normal-release.apk
    - AIMSICD/build/outputs/apk/md5sum.txt
    - AIMSICD/build/outputs/apk/sha1sum.txt
  on:
    repo: CellularPrivacy/Android-IMSI-Catcher-Detector
    tags: true

addons:
  coverity_scan: #Scan results: http://scan.coverity.com/projects/3346
    project:
      name: "CellularPrivacy/Android-IMSI-Catcher-Detector"
    notification_email: annoyed@coverity.notifications
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: master

notifications:
  hipchat:
    - secure: "I2XmQkFCyKZHW2NeClYyl3FND80YkqLtYo+Rn3ftS4xjEg6VfGgDv6AlvQ+b+oZg7RZI6nKia9OLZxAxVBOHw6UcJJnurJx4hfAIBZAihIiNpZPj1c9wGgv4D+M6zi3rgbJRZ2Tz6IKJvHC+CD3LApeJR9kH15lDWbD7YZ0UI7E="
>>>>>>> refs/remotes/CellularPrivacy/development
